### ISSUE TITLE
Should not show passwords while typing

### ISSUE THREAD

**Issue by felipesabino** [finnp/node-travisjs#11]
It currently shows the password while it's been typed, but it should be hidden for security reasons

![screenshot 2015-01-27 09 21 19](https://cloud.githubusercontent.com/assets/700480/5923141/f6f80ac4-a605-11e4-95ee-4b5bd3533702.png)

**Comment by matiassingers** [comment]
I believe this is actually a part of [`git-travis`](https://github.com/davglass/git-travis), think it would make more sense to create this issue there.

More specifically this line: [davglass/git-travis/ lib/index.js#L252](https://github.com/davglass/git-travis/blob/master/lib/index.js#L252)

**Comment by felipesabino** [comment]
I agree and just did it, thanks for pointing out 

https://github.com/davglass/git-travis/issues/5

**Comment by finnp** [comment]
I don't remember at all that the `git-travis` module prompts for log-in data. That shouldn't happen at all. I am going to think about replacing it or creating a PR so that this is not necessary.

**Comment by finnp** [comment]
Ah alright, this prompt only appears on private repos.

**Comment by felipesabino** [comment]
@finnp It seem that this was fixes by [git-travis@1.0.0](https://github.com/davglass/git-travis/issues/5#issuecomment-71859431)
